mozilla-ai/any-llm

pyproject.toml, src/any_llm/providers/ollama/ollama.py
- Introduced Ollama SDK dependency in `pyproject.toml`.
- Updated `OllamaProvider` to utilize the Ollama SDK for chat completions.
- Improved error handling for missing Ollama installation.
- Cleaned up response handling and message formatting.
=> feat: add Ollama SDK support and update dependencies

README.md
- Move Key Features section before Motivation for better flow
- Add user-focused bullet points highlighting simple interface and developer experience
=> Improve README structure

src/any_llm/providers/aws/aws.py, tests/unit/test_aws_provider.py
=> feat: add api_base to aws

src/any_llm/providers/azure/azure.py, src/any_llm/providers/cerebras/cerebras.py, src/any_llm/providers/cohere/cohere.py, src/any_llm/providers/watsonx/watsonx.py
Relies on [test_providers_raise_MissingApiKeyError](https://github.com/mozilla-ai/any-llm/commit/cf1a75524ba1ca795c302902e9c42a04e4ec459c) to verify nothing broke.
=> refactor: Drop duplicate code for MissingApiKeyError.

src/any_llm/providers/google/google.py, src/any_llm/providers/google/utils.py, tests/integration/test_streaming.py
https://github.com/mozilla-ai/any-llm/actions/runs/16622603684/job/47030696239
=> feat(google): Support `stream`.

scripts/hooks.py, src/any_llm/provider.py, src/any_llm/providers/anthropic/anthropic.py, src/any_llm/providers/aws/aws.py, src/any_llm/providers/azure/azure.py, src/any_llm/providers/cerebras/cerebras.py, src/any_llm/providers/cohere/cohere.py, src/any_llm/providers/fireworks/fireworks.py, src/any_llm/providers/google/google.py, src/any_llm/providers/groq/groq.py, src/any_llm/providers/huggingface/huggingface.py, src/any_llm/providers/mistral/mistral.py, src/any_llm/providers/ollama/ollama.py, src/any_llm/providers/openai/base.py, src/any_llm/providers/together/together.py, src/any_llm/providers/watsonx/watsonx.py
I'm not sold on this being the final solution, but it's a step forwards at least to avoid any hardcoding in the hook
=> feat: streaming support as class attribute

src/any_llm/providers/mistral/utils.py
Fixes types errors described in #67
=> fix(mistral): Replace `hasattr` with `getattr` and defaults.

src/any_llm/providers/anthropic/utils.py, tests/unit/providers/test_anthropic_provider.py
- Refactor `_convert_tool_choice`.
- Extend `test_anthropic_provider`.
=> fix(anthropic): Handle `tool_choice=required` conversion.

src/any_llm/providers/anthropic/utils.py, tests/unit/providers/test_anthropic_provider.py
Integration tests: https://github.com/mozilla-ai/any-llm/actions/runs/16938318602
=> fix(anthropic): Handle messages inside agent loop.

.github/pull_request_template.md
Adding a PR template. I don't think we need to follow it closely (yet) but may be good for external contributions. Let me know what you think and definitely am open to suggestions (this is a total spitball)
=> ci: PR template

.github/workflows/tests-integration.yaml, tests/conftest.py, tests/integration/test_response_format.py
https://github.com/mozilla-ai/any-llm/actions/runs/16986708879/job/48157076250
=> tests: Enable `huggingface` integration tests.

pyproject.toml, src/any_llm/provider.py, src/any_llm/providers/llamacpp/__init__.py, src/any_llm/providers/llamacpp/llamacpp.py, tests/conftest.py, tests/constants.py, tests/integration/test_completion.py, tests/integration/test_reasoning.py, tests/integration/test_response_format.py, tests/integration/test_responses.py, tests/integration/test_streaming.py, tests/integration/test_tool.py
Support for Llama.cpp! (Llama-server)
=> feat: add llamacpp

CONTRIBUTING.md
Adds docs on contributing a new provider to `CONTRIBUTING.md`!
PR Type: 📚 Docs
Fixes #171
=> docs: How To Contribute A New Provider

src/any_llm/utils/aio.py
Copied from `any-agent` 😎
Closes #200
=> feat(async): Async runner for sync environments

src/any_llm/providers/anthropic/anthropic.py, src/any_llm/providers/anthropic/utils.py, src/any_llm/providers/google/utils.py, src/any_llm/providers/llamafile/llamafile.py, src/any_llm/providers/mistral/mistral.py, src/any_llm/providers/mistral/utils.py, src/any_llm/providers/ollama/ollama.py, src/any_llm/types/completion.py, tests/integration/test_reasoning.py
Google, anthropic, and mistral didn't properly support reasoning when streaming. Added an integration test and fixed those providers
=> feat(reasoning): integration test for streaming + reasoning

src/any_llm/providers/google/google.py, src/any_llm/providers/google/utils.py
=> feat(google): Add model listing support

src/any_llm/providers/fireworks/fireworks.py
=> feat(fireworks): Enable model listing support in FireworksProvider

src/any_llm/providers/cerebras/cerebras.py, src/any_llm/providers/cerebras/utils.py
=> feat(cerebras): Add model listing support in CerebrasProvider

src/any_llm/providers/xai/xai.py
Migrate xAI provider to async
PR Type: 🆕 New Feature
Closes #220
=> feat(async): migrat xAI provider to async

src/any_llm/providers/google/google.py
NOTE: Untested until I get my hands on an Google API key 🥀 
PR Type: 🆕 New Feature
Closes #208
=> feat(async): Migrate google provider to async

tests/conftest.py
It is failing on main because of missing key: https://github.com/mozilla-ai/any-llm/actions/runs/17237406658
=> tests: Add `AZUREOPENAI` placeholder.

CONTRIBUTING.md
Include ground rules for contributors.
PR Type: 📚 Documentation
=> docs(Contributing): Update CONTRIBUTING.md

src/any_llm/provider.py, tests/unit/test_provider.py
Better parsing for model id string
=> fix(provider): model parsing fix

pyproject.toml, src/any_llm/providers/cerebras/cerebras.py
=> feat: no more instructor in cerebras

src/any_llm/providers/aws/aws.py, src/any_llm/providers/aws/utils.py, tests/conftest.py, tests/unit/providers/test_aws_provider.py
- Refactor all logic into `_convert_params`.
- Fix `inferenceConfig` args were not being handled properly (i.e. `max_tokens` -> `maxTokens`).
- Fix `tool_choice` not handled.
=> fix(aws): `kwargs` were not being handled.

src/any_llm/providers/gemini/gemini.py, src/any_llm/providers/gemini/utils.py, tests/unit/providers/test_google_provider.py
Fix bug where parallel tool calls weren't being added to the response
=> fix: parallel tool call handling

docs/api/types/completion.md, docs/api/types/model.md, docs/api/types/provider.md, docs/api/types/responses.md, mkdocs.yml
Render information about the types we use into the docs
=> chore: docs for types

src/any_llm/providers/llamafile/llamafile.py
Only override `_verify_and_set_api_key`.
=> fix(llamafile): Don't onverride `__init__`.

src/any_llm/providers/openrouter/openrouter.py
Fixes usage with `response_format` and `tools`.
=> fix(openrouter): Only override `_convert_completion_params`.

src/any_llm/providers/together/utils.py, tests/unit/providers/test_together_provider.py
A chunk with empty choices just signals that the model is done returning chunks.
=> fix(together): Don't raise exception with empty choices.
