mozilla-ai/any-llm

- src/any_llm/providers/mistral/mistral.py
`verify_kwargs` was unnecessarily raising an exception.
- main
- This PR
> fix(mistral): Allow `stream` kwarg.

- src/any_llm/providers/helpers.py
- src/any_llm/providers/ollama/utils.py
Relates to https://github.com/BerriAI/litellm/issues/11680 and https://github.com/mozilla-ai/any-llm/issues/26:
OpenAI ChatCompletion base type doesn't have a 'reasoning' key, which means accepting that as the standard for LLM output requires us to hack around passing a reasoning key.
For the time being, we can attach a `reasoning` attribute to the Completion object (and delta for streaming), but it ejects us from type checking and isn't ideal in the long term. I think we need to figure out a reliable way to support providing reasoning info. 
Maybe it means support for the `responses` API format, or maybe it means extending the OpenAI completion into our own type. Not sure.
> feat: attach reasoning to OpenAI ChatCompletion 

- src/any_llm/providers/anthropic/anthropic.py
Check is already happening inside `verify_kwargs`.
> fix(anthropic): Drop duplicated `stream` + `response_format` check.

- src/any_llm/provider.py
- src/any_llm/providers/anthropic/anthropic.py
- src/any_llm/providers/aws/aws.py
- src/any_llm/providers/azure/azure.py
- src/any_llm/providers/cerebras/cerebras.py
- src/any_llm/providers/cohere/cohere.py
- src/any_llm/providers/deepseek/deepseek.py
- src/any_llm/providers/fireworks/fireworks.py
- src/any_llm/providers/google/google.py
- src/any_llm/providers/groq/groq.py
- src/any_llm/providers/huggingface/huggingface.py
- src/any_llm/providers/mistral/mistral.py
- src/any_llm/providers/ollama/ollama.py
- src/any_llm/providers/openai/base.py
- src/any_llm/providers/together/together.py
- src/any_llm/providers/watsonx/watsonx.py
- tests/unit/providers/test_anthropic_provider.py
- tests/unit/providers/test_aws_provider.py
- tests/unit/providers/test_azure_provider.py
- tests/unit/providers/test_cohere_provider.py
- tests/unit/providers/test_google_provider.py
- tests/unit/providers/test_huggingface_provider.py
- tests/unit/providers/test_watsonx_provider.py
As we've expanded any-llm functionality, the _make_api_call function name no longer makes sense.
> chore: clean up naming

- src/any_llm/api.py
- src/any_llm/provider.py
- src/any_llm/types/responses.py
- Added typing for response API
- Unit tests/integration tests pass
- Python 3.11+ supports `TypeAlias` type hint, which we should probably use on any type aliases (unless we're targeting <=3.10 compatibility) in a separate PR. I'll raise an issue. (UPDATE: looks like we're >=3.11, I'll raise the issue.)
- I'm only adding aliases for the first level of OpenAI input models. Let me know if we want to go deeper than that
> feat: Add typing for responses API

- src/any_llm/providers/aws/aws.py
* Added a check to raise a ValueError if the 'stream' option is provided alongside 'response_format', as it is not supported.
* Removed redundant stream assignment from the main logic for clarity.
> fix(aws): Prevent stream option with response_format (#151)

- .github/workflows/tests-integration.yaml
- src/any_llm/providers/cohere/cohere.py
- tests/integration/test_response_format.py
- tests/unit/providers/test_cohere_provider.py
- Adds support for `response_format` for Cohere provider
- Enables `response_format` integration tests for Cohere
- The way that Cohere handles structured outputs is significantly different than Fireworks so I wrote logic in the Cohere provider instead of making a universal helper function. I think that something like an abstract method or smaller formatting function for Pydantic models specifically could be helpful if/when we want to do things like validate desired JSON schemas on a per-provider basis.
- On that note, there's a ton of limitations in the way Cohere does structured outputs and I'm letting the Cohere client handle it.
> feat: response_format for cohere provider

- src/any_llm/providers/google/google.py
- tests/unit/providers/test_anthropic_provider.py
- tests/unit/providers/test_google_provider.py
We were concatenating the user messages into a single string (not sure why) and leaving out other messages (i.e. assistant responses and tool call results).
This was an incorrect implementation for both agent loops and multi-turn conversations (because assistant responses were not being fed back to the model).
See https://ai.google.dev/gemini-api/docs/text-generation#rest_6 for reference.
> fix(google): Handle multiple input `messages` appropriately.

- src/any_llm/providers/google/utils.py
- src/any_llm/providers/llama/llama.py
- src/any_llm/providers/llama/utils.py
- src/any_llm/tools.py
- tests/unit/providers/test_google_utils.py
- tests/unit/test_tools.py
Advanced callable conversion logic: handle poorly typed args (list vs list[str] etc), pydantic typed args, Optionals, and Unions.
Added a unit test to check that the conversions look reasonable and ran some integration style tests locally, but decided to avoid adding an integration test since I think I've got the important checks handled in the unit test.
> feat(tools): Enhance callable_to_tool to support complex types

- src/any_llm/providers/huggingface/huggingface.py
- tests/unit/providers/test_huggingface_provider.py
Argument was being ignored. Needs to be passed as `base_url` to the client.
> fix(huggingface): Handle `config.api_base`.

- src/any_llm/providers/google/google.py
- tests/unit/providers/test_google_provider.py
Matching https://github.com/mozilla-ai/any-llm/pull/252.
- `reasoning_effort="auto"` -> (Default) don't pass any thinking config.
- `reasoning_effort!="auto"` -> Enable thinking and map reasoning_effort to thinking budgets.
- `reasoning_effort=None` -> Disable thinking.
> fix(google): Handle `reasoning_effort` defaults.

- src/any_llm/providers/openai/base.py
because we don't know if the model being inferenced supports it.
Gpt-4.1 doesn't support reasoning_effort in completion api, so we can't set it by default. I'm open to changes here if you have thoughts, @daavoo .
🐛 Bug Fix
> fix(openai): Update default `_DEFAULT_REASONING_EFFORT` to `None`

- src/any_llm/providers/google/google.py
- tests/unit/providers/test_google_provider.py
Google doesn't have the max_tokens param
> fix(google): max_tokens translation

- src/any_llm/providers/cohere/utils.py
- src/any_llm/providers/mistral/utils.py
- tests/unit/providers/test_cohere_provider.py
- tests/unit/providers/test_mistral_provider.py
This PR refactors the `_patch_messages` utility in the Cohere and Mistral provider modules (`src/any_llm/providers/cohere/utils.py` and `src/any_llm/providers/mistral/utils.py`).
The previous implementation did not handle certain edge cases in agentic loops, which could lead to errors when a `tool` message was not preceded by an `assistant` message. This update introduces validation to ensure the correct message sequence and improves the logic to handle more complex conversational flows.
Additionally, new unit tests have been added in `tests/unit/providers/test_cohere_provider.py` and `tests/unit/providers/test_mistral_provider.py` to cover these new edge cases and prevent future regressions.
-   💅 Refactor
Fixes #316
> refactor(mistral, cohere): Improve message patching robustness

- src/any_llm/provider.py
- src/any_llm/utils/aio.py
- Move `RuntimeError` handling to inside `run_async_in_sync`. No need to repeat the `get_running_loop` block.
> fix(aio): Don't raise RuntimeError if `INSIDE_NOTEBOOK`.

- src/any_llm/providers/mistral/utils.py
- tests/unit/providers/test_mistral_provider.py
In order to reduce confusion, any-llm won't prevent people from making a call to mistral with a tool message with no assistant message before it. Then, if Mistral throws an exception it is clear that it is not any-llm that has the limitation
Relates to https://github.com/mozilla-ai/any-agent/issues/787
> fix: allow for malformed messages to be passed to mistral

- .github/workflows/tests-integration.yaml
Sometime you only make a change for one provider and you want to run the integration test just on that feature or provider.
> manually run can pass args

- src/any_llm/providers/gemini/gemini.py
- tests/unit/providers/test_google_provider.py
In #401 we stopped overriding `Provider.__init__` and thus we started to rely again on the default `Provider._verify_and_set_api_key`.
We need to provide a custom implementation that checks for both API key options instead of the plain string with a `/`.
- Added `test_gemini_initialization_with_env_var_api_key` and `test_vertexai_initialization_with_env_var_api_key`.
> fix(gemin): Implement `_verify_and_set_api_key`.

- .github/workflows/tests-integration.yaml
- tests/constants.py
- tests/integration/test_completion.py
- tests/integration/test_embedding.py
- tests/integration/test_list_models.py
- tests/integration/test_reasoning.py
- tests/integration/test_response_format.py
- tests/integration/test_responses.py
- tests/integration/test_streaming.py
- tests/integration/test_tool.py
This PR adds support for an env var that gets passed between integration test and the github action to not let tests fail if the key is expected to be there. This helps prevent tests being silently skipped.
> fix: accept an expected_providers env var

- tests/integration/test_list_models.py
We don't want to use the `api_base` used for completion.
> tests: Fix `test_list_models` for `huggingface`.
